name: Deploy GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    permissions:
      contents: read  # <--- allows to read repo
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: master
          
     #  给当前服务器安装node
      - name: UseNode
        uses: actions/setup-node@v2
        with:
         node-version: 16 # node版本
         cache: "yarn"
         
      - name: Set up Git
        run: |
          git config --global user.name "qiangqiang"
          git config --global user.email "qiangq24@outlook.com"
   
      - name: Reattach HEAD
        run: git checkout "$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
          
     #  下载项目依赖    
      - name: Install
        run: yarn install


      # 生成静态文件
      - name: Build
        run:  yarn run blogs:build

      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.BLOG_DEPLOY }} # 生成的 secret
          BRANCH: build # 部署到 build
          FOLDER: public # vuepress 生成的静态文件存放的地方
          CLEAN: true
